name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch: 
    {}


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.15
          - 1.16
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: make ${{ matrix.go }}
    - name: Push
      run: make push
